- name: Transfer the docker script
  ansible.builtin.copy:
    src: scripts/unix/docker_info_local.sh
    dest: /tmp/docker_enum.sh
    mode: 0777
- name: Run the script and produce the output
  ansible.builtin.command: /tmp/docker_enum.sh
  changed_when: false
  register: docker_enum
- name: Print the output
  ansible.builtin.debug:
    msg: "{{ docker_enum.stdout_lines }}"
